language: node_js
node_js:
- '5.8'

apt addons:

before_install:

before_script:
- npm install -g webpack
- npm install -g karma-cli
- npm install -g mocha
- npm install -g chai
# The below will allow script to run in Firefox
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3

script:

after_success:

after_failure:

before_deploy:

deploy:

after_deploy:

after_script:
